# Enable the health endpoint for Elastic Beanstalk
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# AWS Secrets Manager Integration
spring.config.import=optional:aws-secretsmanager:Tss_SalesTax_Ora_Dev01

# Map keys from the Secret to Spring properties
spring.datasource.url=${dburl}
spring.datasource.username=${dbusername}
spring.datasource.password=${dbpassword}
