# Enable the health endpoint for Elastic Beanstalk
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# AWS Secrets Manager Integration
spring.config.import=optional:aws-secretsmanager:Tss_SalesTax_Ora_Dev01
